//
//  UserSDK.swift
//  UserSDK
//
//  Created by Andrzej Puczyk on 08/03/2019.
//  Copyright © 2019 Future Mind, Sp. z o.o. All rights reserved.
//

import UIKit
import UserNotifications

public class UserSDK {

    /**
     Static instance of once initialized SDK
     */
    static public var `default`: UserSDK?

    /**
     Public REST API credential.

     Generated on Dashboard -> Settings -> App Settings -> Advanced -> Public REST API keys. It will be used by the SDK to send or get all data from user.com application using REST API.
     */
    public private(set) var apiKey: String

    /**
     Base application url {baseURL}.user.com
     */
    public private(set) var baseURL: String

    /**
     State of automatically activities (screen logs) tracking.
    */
    public private(set) var shouldTrackActivities: Bool

    /**
     Remote notifications delegate
     */
    public var notificationDelegate: RemoteNotificationDelegate?

    /**
     User identifier generated by user.com
    */
    public var userId: String?

    /**
     Public SDK initialization method.

     - Parameter application: Application instance.
     - Parameter apiKey: Public REST API credential.
     - Parameter baseURL: Base application url {baseURL}.user.com.
     - Parameter shouldTrackActivities: State of automatically activities (screen logs) tracking.

     - Returns: SDK Instance
     */
    public init(
        application: UIApplication,
        apiKey: String,
        baseURL: String,
        shouldTrackActivities: Bool)

}

// MARK: Base functions

extension UserSDK {

    /**
     Send default user data (and possibly create new user if not exist)
     */
    public func ping(_ completion: ((Bool, Error?) -> Void)? = nil)

    /**
     Send event

     - Parameter name: Event name.
     - Parameter params: Data params.
     */
    public func sendEvent(with name: String, params: [String: Any], _ completion: ((Bool, Error?) -> Void)? = nil)

    /**
     Send screen

     - Parameter name: Screen name.
    */
    public func trackScreen(with name: String, _ completion: ((Bool, Error?) -> Void)? = nil)

}

// MARK: Custom User data

extension UserSDK {

    public enum UserDataKey: String {
        case firstName = "first_name"
        case lastName = "last_name"
        case email = "email"
        case phone = "phone"
        case userId = "user_id"
    }

    /**
     Set user data
     (If you want to remove previously added value for key, set the value to 'nil')
     */
    public func setUserData(_ userData: [UserDataKey: String?], _ completion: ((Bool, Error?) -> Void)? = nil)

    /**
     Set custom user data
     */
    public func setCustomUserData(_ userData: [String: Any?], _ completion: ((Bool, Error?) -> Void)? = nil)

}

// MARK: Notifications

extension UserSDK {

    public func registerForRemoteNotifications(options: UNAuthorizationOptions, notificationDelegate: RemoteNotificationDelegate? = nil)

    internal func setNotificationClicked(_ notificationId: String)

}

// MARK: Logout

extension UserSDK {

    /**
     Logout user from app/SDK and wipe all the data

     ### Important:
     Should be used wisely; in case of internet connection problems, all the data will still be removed.
     */
    public func logout(_ completion: ((Bool, Error?) -> Void)? = nil)

}
